package rules;

import riasec.backend.model.classes.HollandCodeTestAttempt
import riasec.backend.model.classes.Profession
import java.util.List;
import java.util.ArrayList;

global List exactMatches;
global List similarMatches;

rule "Match Professions to Test Takers Holland Code"
salience 2
when
    $testAttempt: HollandCodeTestAttempt()
    $profession: Profession()
then
    List<String> testTakerHollandCodes = $testAttempt.getResult();
    String professionHollandCode = $profession.getHollandCode();

    for(String code: testTakerHollandCodes){
        if (code.equals(professionHollandCode)){
            exactMatches.add($profession);
        }
        int count = 0;

        for (int i = 0; i < code.length(); i++) {
           if (professionHollandCode.contains(String.valueOf(code.charAt(i)))) {
               count++;
            }
         }
         if(count >= 3) {
            similarMatches.add($profession);
         }
    }

end

